export const STRATEGY_TYPES = {
  // 购买策略

  TWITTER_FOLLOWERS: "TWITTER_FOLLOWERS",
  TWITTER_POSTS: "TWITTER_POSTS",
  KEY_PRICE: "KEY_PRICE",
  WHITELIST: "WHITELIST",
  // 平均阅读量
  TWITTER_VIEWS: "TWITTER_VIEWS",
  // 平均 Like 量
  TWITTER_FAVS: "TWITTER_FAVS",

  // 出售策略
  BENEFIT: "BENEFIT",
  HOLDING_DURATION: "HOLDING_DURATION",
  SPECIFY_LIST: "SPECIFY_LIST",
};

export const STRATEGY_OPERATORS = {
  AND: "AND",
  OR: "OR",
};
