export const STRATEGY_TYPES = {
  // 购买策略
  ACCOUNT_BRIDGED_AMOUNT: "ACCOUNT_BRIDGED_AMOUNT",
  TWITTER_FOLLOWERS: "TWITTER_FOLLOWERS",
  TWITTER_POSTS: "TWITTER_POSTS",
  ACCOUNT_NONCE: "ACCOUNT_NONCE",
  KEY_PRICE: "KEY_PRICE",
  WHITELIST: "WHITELIST",

  // 出售策略
  BENEFIT: "BENEFIT",
  HOLDING_DURATION: "HOLDING_DURATION",
  SPECIFY_LIST: "SPECIFY_LIST"
};

export const STRATEGY_OPERATORS = {
  AND: "AND",
  OR: "OR",
};
